from __future__ import annotations

# Market
MARKET_CONFIRMED_UPTREND = "MARKET_CONFIRMED_UPTREND"
MARKET_RALLY_ATTEMPT = "MARKET_RALLY_ATTEMPT"
MARKET_UNDER_PRESSURE = "MARKET_UNDER_PRESSURE"
MARKET_CORRECTION = "MARKET_CORRECTION"
MARKET_NEW_BUY_ALLOWED = "MARKET_NEW_BUY_ALLOWED"
MARKET_NEW_BUY_NOT_ALLOWED = "MARKET_NEW_BUY_NOT_ALLOWED"

# Technical
RS_SCORE_ABOVE_70 = "RS_SCORE_ABOVE_70"
RS_SCORE_ABOVE_80 = "RS_SCORE_ABOVE_80"
RS_SCORE_ABOVE_90 = "RS_SCORE_ABOVE_90"
PRICE_ABOVE_MA50 = "PRICE_ABOVE_MA50"
PRICE_ABOVE_MA200 = "PRICE_ABOVE_MA200"
PRICE_BELOW_MA50 = "PRICE_BELOW_MA50"
BREAKOUT_CONFIRMED = "BREAKOUT_CONFIRMED"
NEAR_52W_HIGH = "NEAR_52W_HIGH"
WARNING_BREAK_MA50 = "WARNING_BREAK_MA50"
WARNING_HIGH_VOLUME_SELLING = "WARNING_HIGH_VOLUME_SELLING"

# Data
DATA_REAL_PROVIDER = "DATA_REAL_PROVIDER"
DATA_DEMO_PROVIDER = "DATA_DEMO_PROVIDER"
DATA_FALLBACK_USED = "DATA_FALLBACK_USED"
DATA_NOT_SAFE_FOR_LLM = "DATA_NOT_SAFE_FOR_LLM"
MISSING_SECTOR_MAPPING = "MISSING_SECTOR_MAPPING"
MISSING_FINANCIAL_DATA = "MISSING_FINANCIAL_DATA"
MISSING_CANDLESTICK_DATA = "MISSING_CANDLESTICK_DATA"

# CANSLIM
CANSLIM_AVAILABLE = "CANSLIM_AVAILABLE"
CANSLIM_SCORE_STRONG = "CANSLIM_SCORE_STRONG"
CANSLIM_SCORE_WEAK = "CANSLIM_SCORE_WEAK"

# Payback
PAYBACK_AVAILABLE = "PAYBACK_AVAILABLE"
VALUATION_BELOW_MOS50 = "VALUATION_BELOW_MOS50"
VALUATION_BELOW_MOS60 = "VALUATION_BELOW_MOS60"
VALUATION_BELOW_MOS70 = "VALUATION_BELOW_MOS70"
VALUATION_EXPENSIVE = "VALUATION_EXPENSIVE"

# Candlestick
CANDLESTICK_BUY_SIGNAL = "CANDLESTICK_BUY_SIGNAL"
CANDLESTICK_SELL_SIGNAL = "CANDLESTICK_SELL_SIGNAL"
CANDLESTICK_NO_SIGNAL = "CANDLESTICK_NO_SIGNAL"
RR_ABOVE_1_5 = "RR_ABOVE_1_5"
RR_BELOW_1_5 = "RR_BELOW_1_5"

UNSAFE_NEGATIVE_REASON = "Data is not safe for real market analysis."
UNSAFE_LLM_INSTRUCTION = "Do not provide real market analysis."
